#!/bin/sh
#
# r53 - AWS Route 53 DNS Record Updater
#
#   Prerequisite
#     awscli
#     jq
#

prog=$(basename $0)
bindir=$(dirname $(readlink -f $0))

echoerr() {
        echo "$@" >&2
}

_msg() {
        local msg="$1"
        if [ -n "$msg" ]; then
                echoerr "$msg"
        fi
}

usage_exit() {
	_msg "$1"
	echoerr "$USAGE"
	exit 1
}

USAGE="AWS Route 53 DNS Record Updater
usage:
  $prog [-p <prof>] update [-t <type>] [-T <ttl>] [-C <comment>] <name> <value>
  $prog [-p <prof>] delete [-t <type>] [-C <comment>] <name>
  $prog [-p <prof>] show [-mc] [-t <type>] <name>
  $prog [-p <prof>] list [-mc]
  $prog [-p <prof>] configure [-n]
  $prog [-p <prof>] show-config
  $prog [-p <prof>] test-name <name>

  Flags:
    -m: minify output by omitting some fields for human-readability.
    -c: instruct jq to make output compact.
    -n: do not query zone id by input zone domain.

  Default values:
    -p = default
    -t <type> = A
    -T <ttl> = 60
    -c <comment> = by $prog on YYYY-mm-dd HH:MM:SS
" # END-QUOTE

LOCKFILE=$prog.lck
DEFAULT_TYPE=A
DEFAULT_TTL=60
DEFAULT_COMMENT="by $prog on $(date '+%Y-%m-%d %H:%M:%S')"

_lock() {
	if ! ln -s $$ $LOCKFILE > /dev/null 2>&1; then
		return 1
	else
		trap '_unlock; exit 1' 1 2 3 11 15
		return 0
	fi
}

_unlock() {
	rm -f $LOCKFILE
	trap 1 2 3 11 15
}

_get_ini_section() {
        local inifile section
        inifile=$1
        section=$2
        if [ -r "$inifile" -a -n "$section" ]; then
                cat "$inifile" | sed -r -n "
                        /^\[$section\]/,/^(\$|\[)/{
                                /^[A-Z]/p
                        }
                " # END-QUOTE
        fi
}

_delete_ini_section() {
        local inifile section
        inifile=$1
        section=$2
        if [ -r "$inifile" -a -n "$section" ]; then
                cat "$inifile" | sed -r "
                        /^\[$section\]/,/^(\$|\[)/{
				/^(\[$section|^[A-Z])/d
                        }
                " # END-QUOTE
        fi
}

_get_zoneid() {
	local domain
	domain=${1:-$HOSTED_ZONE_DOMAIN}
	profile=${2:-$AWSCLI_PROFILE}
	aws --profile $profile route53 list-hosted-zones --query 'HostedZones[?Name == `'$domain'.`].Id' --output text | sed 's/\/hostedzone\///'
}

_get_domain() {
	local id
	id=${1:-$HOSTED_ZONE_ID}
	profile=${2:-$AWSCLI_PROFILE}
	aws --profile $profile route53 get-hosted-zone --id $id | jq -r .HostedZone.Name | sed -r 's/\.+$//'
}

_qualify() {
	local name fqdn
	name=$1
	if [ -n "$HOSTED_ZONE_DOMAIN" ]; then
		if [ "$name" = "@" ]; then
			fqdn="$HOSTED_ZONE_DOMAIN"
		elif echo "$name" | egrep -q "$HOSTED_ZONE_DOMAIN"'\.*$'; then
			fqdn="$name"
		else
			fqdn=$(echo "$name" | sed -r 's/\.+$//').$HOSTED_ZONE_DOMAIN
		fi
	else
		fqdn=""
	fi
	fqdn=$(echo "$fqdn" | sed -r 's/\.+$//').
	echo "$fqdn"
}

_get_change_status() {
	local changeid
	changeid=$1

	aws --profile $AWSCLI_PROFILE route53 get-change --id "$changeid" | jq -r .ChangeInfo.Status
}

_wait_for_sync() {
	local changeid status _prefix

	changeid=$1
	if [ -z "$changeid" ]; then
		echoerr "Missing changeid ($changeid)."
		return 1
	fi

	_prefix=
	while true; do
		status=$(_get_change_status $changeid)
		echoerr -n ${_prefix:-"Waiting $changeid to be sync: "}$status
		_prefix=", "
		if [ "$status" = "INSYNC" ]; then
			break
		fi
		sleep 10
	done
	if [ -n "$_prefix" ]; then
		echoerr "."
	fi
}

list() {
	local OPTIND jqopt minified result
	while getopts "cm" opt
	do
		case "$opt" in
			c) jqopt="-c" ;;
			m) minified=yes ;;
			*) ;;
		esac
	done
	shift $(( $OPTIND - 1 ))

	result=$(aws --profile $AWSCLI_PROFILE route53 list-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID)

	if [ "$minified" = "yes" ]; then
		echo "$result" | jq $jqopt -r '.ResourceRecordSets | sort_by(.Type, .Name) | .[] | [ .Name, .Type, .TTL, [.ResourceRecords[].Value]]'
	else
		echo "$result" | jq $jqopt .
	fi
}

get() {
	local OPTIND name fqdn rectype jqopt minified result
	while getopts "cmt:" opt
	do
		case "$opt" in
			c) jqopt="-c" ;;
			m) minified=yes ;;
			t) rectype=$(echo $OPTARG | tr a-z A-Z) ;;
			*) ;;
		esac
	done
	shift $(( $OPTIND - 1 ))

	name=$1
	fqdn=$(_qualify $name)
	rectype=${rectype:-$DEFAULT_TYPE}
	if [ -z "$HOSTED_ZONE_ID" -o -z "$fqdn" -o -z "$rectype" ]; then
		echoerr "Missing HOSTED_ZONE_ID ($HOSTED_ZONE_ID), fqdn ($fqdn) or rectype ($rectype)."
		return 1
	fi

	result=$(aws --profile $AWSCLI_PROFILE route53 list-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --query "ResourceRecordSets[?Name == '$fqdn' && Type == '$rectype'] | [0]")
	
	if [ "$minified" = "yes" ]; then
		echo "$result" | jq $jqopt -r '[ .Name, .Type, .TTL, [.ResourceRecords[].Value]]'
	else
		echo "$result" | jq $jqopt .
	fi
}

delete() {
	local OPTIND name fqdn rectype comment json record result
	while getopts "C:t:" opt
	do
		case "$opt" in
			C) comment="$OPTARG" ;;
			t) rectype=$(echo $OPTARG | tr a-z A-Z) ;;
			*) ;;
		esac
	done
	shift $(( $OPTIND - 1 ))

	name=$1
	fqdn=$(_qualify $name)
	rectype=${rectype:-$DEFAULT_TYPE}
	comment=${comment:-"DELETE $fqdn $rectype $DEFAULT_COMMENT"}
	if [ -z "$HOSTED_ZONE_ID" -o -z "$fqdn" -o -z "$rectype" ]; then
		echoerr "Missing HOSTED_ZONE_ID ($HOSTED_ZONE_ID), fqdn ($fqdn) or rectype ($rectype)."
		return 1
	fi

	record="$(get -m $fqdn $rectype)"
	if [ -z "$record" -o "$record" = "null" ]; then
		echoerr "Couldn't find $fqdn $rectype."
		return 1
	fi

	json=$(cat <<EOB
  {
    "Comment": "$comment",
    "Changes": [
      {
        "Action": "DELETE",
        "ResourceRecordSet": $record
      }
    ]
  }
EOB
)

	result=$(aws --profile $AWSCLI_PROFILE route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch "$json" | jq -c .)
	echo "$result"

	changeid=$(echo $result | jq -r .ChangeInfo.Id)
	_wait_for_sync $changeid
}

upsert() {
	local OPTIND name fqdn rectype ttl value comment json result changeid
	while getopts "C:t:T:" opt
	do
		case "$opt" in
			C) comment="$OPTARG" ;;
			t) rectype=$(echo $OPTARG | tr a-z A-Z) ;;
			T) ttl="$OPTARG" ;;
			*) ;;
		esac
	done
	shift $(( $OPTIND - 1 ))

	name=$1
	fqdn=$(_qualify $name)
	value=$2
	rectype=${rectype:-$DEFAULT_TYPE}
	ttl=${ttl:-$DEFAULT_TTL}
	comment=${comment:-"UPSERT $fqdn $rectype [$value] $DEFAULT_COMMENT"}
	if [ -z "$HOSTED_ZONE_ID" -o -z "$fqdn" -o -z "$value" ]; then
		echoerr "Missing HOSTED_ZONE_ID ($HOSTED_ZONE_ID), fqdn ($fqdn) or rectype ($rectype)."
		return 1
	fi

	if [ "$rectype" = "TXT" -o "$rectype" = "SPF" ]; then
		value="\\\"$value\\\""
	fi

	json=$(cat <<EOB
  {
    "Comment": "$comment",
    "Changes": [
      {
        "Action": "UPSERT",
        "ResourceRecordSet": {
          "Name": "$fqdn",
          "Type": "$rectype",
          "TTL": $ttl,
          "ResourceRecords": [
            {
              "Value": "$value"
            }
          ]
        }
      }
    ]
  }
EOB
)

	result=$(aws --profile $AWSCLI_PROFILE route53 change-resource-record-sets --hosted-zone-id $HOSTED_ZONE_ID --change-batch "$json" | jq -c .)
	echo "$result"

	changeid=$(echo $result | jq -r .ChangeInfo.Id)
	_wait_for_sync $changeid
}

configure() {
	local OPTIND noquery r53_profile zoneid awscli_profile domain yesno currcontents
	while getopts "n" opt
	do
		case "$opt" in
			n) noquery="yes" ;;
			*) ;;
		esac
	done
	shift $(( $OPTIND - 1 ))

	while true; do
		read -p "r53 Profile [$R53_PROFILE]: " r53_profile
		if [ -n "${r53_profile:=$R53_PROFILE}" ]; then
			break
		fi
	done

	while true; do
		read -p "AWS CLI Profile [$AWSCLI_PROFILE]: " awscli_profile
		if [ -n "${awscli_profile:=$AWSCLI_PROFILE}" ]; then
			break
		fi
	done

	while true; do
		read -p "Hosted Zone Domain [$HOSTED_ZONE_DOMAIN]: " domain
		if [ -n "${domain:=$HOSTED_ZONE_DOMAIN}" ]; then
			break
		fi
	done

	if [ -z "$HOSTED_ZONE_ID" -a "$noquery" != "yes" ]; then
		HOSTED_ZONE_ID=$(_get_zoneid $domain $awscli_profile)
	fi

	while true; do
		read -p "Hosted Zone ID [$HOSTED_ZONE_ID]: " zoneid
		if [ -n "${zoneid:=$HOSTED_ZONE_ID}" ]; then
			break
		fi
	done

	if [ -f "$HOME/.r53rc" ]; then
		read -p "Overwrite existing configuration? [N/y]: " yesno
		if echo "$yesno" | egrep -v '^[yY]' > /dev/null 2>&1; then
			echoerr "Do nothing."
		fi
		currcontents=$(_delete_ini_section "$HOME/.r53rc" "$r53_profile")
	fi

	cat <<EOB> $HOME/.r53rc
$currcontents
[$r53_profile]
AWSCLI_PROFILE=$awscli_profile
HOSTED_ZONE_ID=$zoneid
HOSTED_ZONE_DOMAIN=$domain
EOB
}

#
# Main
#
R53_PROFILE=default
AWSCLI_PROFILE=default
HOSTED_ZONE_ID=
HOSTED_ZONE_DOMAIN=

while getopts "p:" opt
do
	case "$opt" in
		p) R53_PROFILE="${OPTARG:-$R53_PROFILE}" ;;
		*) usage_exit ;;
	esac
done
shift $(( $OPTIND - 1 ))

if [ -f "$HOME/.r53rc" ]; then
	config=$(_get_ini_section "$HOME/.r53rc" "$R53_PROFILE")
	eval "$config"
fi

command=$1
shift

case "$command" in
	update|upsert)
		if ! _lock; then
		      echoerr "Another process seems to be running. Aborting..."
		      exit 1
		fi
		upsert "$@"
		_unlock
		;;
	delete)
		if ! _lock; then
		      echoerr "Another process seems to be running. Aborting..."
		      exit 1
		fi
		delete "$@"
		_unlock
		;;
	list)
		list "$@"
		;;
	show|get)
		get "$@"
		;;
	configure)
		configure "$@"
		;;
	show-config)
		test -f "$HOME/.r53rc" && _get_ini_section "$HOME/.r53rc" "$R53_PROFILE"
		;;
	test-name|testname)
		_qualify "$1"
		;;
	*)
		usage_exit
		;;
esac

